apiVersion: v1
kind: Pod
metadata:
    name: casestudy2-nginx-helloworld
    labels:
       app: web
spec:
  containers:
   - name: nginx-cs2
     image: kommuri44/nginx_casestudy2
     ports:
       - name: nginx-port
         containerPort: 80
   - name: helloworld-cs2
     image: kommuri44/helloworld_casestudy2
     ports:
       - name: helloworldport1
         containerPort: 8080
       - name: helloworldport2
         containerPort: 8081
