---
apiVersion: v1
kind: Service
metadata:
  name: emiratescs-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: emiratescs-port
    protocol: TCP
    name: emirateshttp
  selector:
    app: emiratescs
